`tf.boolean_mask()`将输入的张量，选定指定维度的数据进行输出

tf.boolean_mask(tensor,mask,name='boolean_mask',axis=None):

1. 参数tensor：输入的张量，维度记为N
2. 参数mask: 用于标记哪些维度的数据输出(True)，哪些维度的数据不输出(False)，维度记为K
3. 参数name：操作的名字
4. 参数axis：沿指定的轴

注意：$K\leq N$；axis是一个0维度的int型tensor，即一个整数，它表示从参数tensor的哪个axis开始mask。默认情况下，axis=0，表示从第一个维度进行mask。一般来说，0 < dim(mask)=K < dim(tensor)=N,mask的大小必须匹配参数tensor的shape的前K维度

# 张量的维度

In [1]:
import tensorflow as tf

a = tf.constant([1,2,3])
print('a的结构: ',a)
print()
sess = tf.Session()
print('a: ',sess.run(a))

a的结构:  Tensor("Const:0", shape=(3,), dtype=int32)

a:  [1 2 3]


a 为一维张量,维度为1

In [2]:
b = tf.constant([[1,2,3]])
print('b的结构: ',b)
print()
sess = tf.Session()
print('b: ',sess.run(b))

b的结构:  Tensor("Const_1:0", shape=(1, 3), dtype=int32)

b:  [[1 2 3]]


b为二维张量，维度值为(1,3)

In [3]:
c = tf.constant([[1,2,3],[4,5,6]])
print('c的结构: ',c)
print()
sess = tf.Session()
print('c: ',sess.run(c))

c的结构:  Tensor("Const_2:0", shape=(2, 3), dtype=int32)

c:  [[1 2 3]
 [4 5 6]]


c为二维张量，维度值为(2,3)

# tf.boolean_mask()

## 1-D 张量的mask

In [4]:
a = tf.constant([1,2,3,4])
mask = [True,False,True,False] # mask需对应a中某些元素
sess = tf.Session()
print(sess.run(tf.boolean_mask(a,mask)))

[1 3]


## 2-D张量的mask

In [5]:
import tensorflow as tf

b = tf.constant([[1,2,3,4],[4,5,6,7],[8,9,1,2]],dtype=tf.int32)
mask = [True,False,True]
sess = tf.Session()
print(sess.run(tf.boolean_mask(b,mask)))

[[1 2 3 4]
 [8 9 1 2]]


## 3-D张量的mask

In [6]:
import numpy as np

a = np.random.randn(3,3,3)
b = np.max(a,axis=-1) # 沿着最后一个维度比较
mask = b > 0.5
print('a: ',a)
print()
print('b: ',b)
print()
print('mask: ',mask)

a:  [[[-0.33846176 -0.4830055  -0.10628448]
  [-0.27707716 -0.02307034  1.711797  ]
  [-1.49439232  0.53137998  0.17385866]]

 [[-0.84534258  0.44280724 -0.39423404]
  [-0.01508783  1.44352154  0.63948286]
  [-0.85265869 -0.0748227  -0.00359441]]

 [[-0.97451997  0.63335422  1.01843759]
  [-0.57418278  0.19962646  1.22451244]
  [ 1.77860163 -1.15927377 -0.60151356]]]

b:  [[-0.10628448  1.711797    0.53137998]
 [ 0.44280724  1.44352154 -0.00359441]
 [ 1.01843759  1.22451244  1.77860163]]

mask:  [[False  True  True]
 [False  True False]
 [ True  True  True]]


In [7]:
sess = tf.Session()
print(sess.run(tf.boolean_mask(a,mask)))

[[-0.27707716 -0.02307034  1.711797  ]
 [-1.49439232  0.53137998  0.17385866]
 [-0.01508783  1.44352154  0.63948286]
 [-0.97451997  0.63335422  1.01843759]
 [-0.57418278  0.19962646  1.22451244]
 [ 1.77860163 -1.15927377 -0.60151356]]


mask匹配参数a的前K维度,即(3,3)